---
- name: Configure apps on Ubuntu host
  hosts: all
  become: true
  vars:
    authorized_keys: # This is my pubkey, you want to replace it. Maybe put it in `vars.yml`?
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE9K1p8B8FRCWJ0Ax4obDu+UsLzGgXDIdTYkCZ8FF54b
  vars_files: # These are my secrets, and they're not very good. Make new and better ones with ansible-vault create!
    - secrets.yml
  roles:
    - name: eugene
      vars:
        env_suffix: -test
    - name: kollektivkart
      vars:
        env_suffix: -test